### PR TITLE
Checked and fixed cards that are also available in my pack but made by othersMaster

### PR DESCRIPTION
**Pull request by MichaelLawrenceDee**
Gearspring Catapult: shouldn't trigger during Standby Phase (should be Continuous) and Effect Relation of Continuous Spells.
Automatic Gearspring Catapult: shouldn't trigger during Standby Phase (should be Continuous) and Initial Activation Counter Placing in code. Tranfer counters shouldn't happen in target.
Gearspring Exploder: Effect isn't properly handled.
Gearspring Spirit (Anime): shouldn't target
Cursed Ivy: Fixed DEFENCE bug
Wings of the Supreme King: Destroy and Damage should be optional + script function variable cleanup
Explosive Urchin (Anime): Player Target and script variables cleanup.
Iron Resolve: "Then," and also added Damage Step activation
Realize Defense: Script Cleanup and DEFENCE error
Comeback: Target should be face-up
Comic Field: Missing function
Devoted Love: Missing 'target/ chain info'
Drop Exchange: Missing 'target/ chain info'
Fair Exchange: Player Target and not a cost
Fool's Dice: Monster leaving the field should only be 1 and script cleanup
Gagaga Thunder: Script Cleanup and incomplete target checking
Golden Form: Missing Effect Resets and unnecessary lines
Gorgon Charm: Wrong condition and wrong card number within script
Hollow Spirit: Missing Player Target, when destroyed function, wrong code for Hollow Ghost
Hollow Ghost: unnecessary code, Missing Player Target, wrong Hollow Spirit code
Offerings to the Bound Deity: shouldn't target
Scrap and Build: should target
Small Resistance: unnecessary field checking
Smoke Mirror: Target checks for target but doesn't target and script cleanup
Spirit Mask: Has ToDeck Category and is optional
Superior Howl: Cost target Checks for cost and contains target flag
Triangle Knight: doesn't check changing of target, only returns 1 card, missing category, effect triggers forced, doesn't contain target flag cards
Trion Barrier: DEFENCE issue.
Wind Witch Ice Bell: Wind Witch that Copy Effect will not be able to copy it, missing Player Target
Wind Witch Winter Bell: Capability to Copy Ice Bell
Wind Witch Crystal Bell: IGNITION should be a quick effect, Capability to Copy Ice Bell
Amazoness Empress: Prevents Instant Fusion, script cleanup
Amazoness Liger: Prevents Instant Fusion, negate attack shouldn't trigger, Battled effect should be optional
Amazoness Audience Room: Activation Timings fixed
Amazoness Substitution: Shouldn't target
Fellow's Gift: Doesn't return at End Phase.

### CODE REVIEW

**Comment by MichaelLawrenceDee** [comment]
I didn't completely merge it, only added Gorgon's Charm for 2nd commit.

**Comment by shadowfox87** [comment]
This has conflicts, can't merge.

**Comment by MichaelLawrenceDee** [comment]
The conflict is Gorgon's Charm, how do I fix that conflict? I already editted it as well.

**Comment by MichaelLawrenceDee** [comment]
I'll try to rename Gorgon's Charm filename and then you can just delete it. Hope that removes the conflict.

**Pull request closed without merging**
