### PR TITLE
Shad3's commits 8/16

### PR DESCRIPTION
**Pull request by Shad3Light**
### New Cards:
- 511005085  Cross Counter Trap
 - type is Trap-Spell Card, made both a spell and a trap
- 511005086  Jump Guard

====

### Fixes:
- None

### CODE REVIEW

**Comment by shadowfox87** [comment]
Hey if you get a chance, please look at MLD's pull request and let me know what new cards were added and if there were any nerfs or if all fixes are ok: https://github.com/shadowfox87/animescripts/pull/53/commits/f483d2d63a1af4f6182123058647f0e9a62b386b

**Comment by Shad3Light** [comment]
OK, I'll look into it when I have time.

**Comment by Shad3Light** [comment]
Summary of what you asked @shadowfox87 :

### New Cards:
- 511002902  Absorbing Lamp
- 511002903  Gearspring Catapult
 - listed CC as scripter, id 511009016
- 511002904  Automatic Gearspring Machine
 - listed CC as scripter, id 511009018
- 511002905  Gearspring Exploder
 - listed CC as scripter, id 511009016
- 511002906  Gearspring Spirit (ネジマキシキガミ)
 - listed CC as scripter, id 511009017
- 511002907  Cursed Ivy
 - listed Lyris as scripter, though no card id yet
- 511002908  Rose Blizzard
 - listed id 511000927
- 511002910  Drill Synchron (anime) (ドリル・シンクロン)
- 511002911  Miracle Locus (anime) (奇跡の軌跡)
- 511002912  Ice Princess Zereort (anime) (零鳥姫リオート・ハルピュイア)
- 511002913  Number 94: Crystalzero (anime)
- 511002914  Wings of the Supreme King
- 511002915  Explosive Urchin
 - I had made this one..., id 511005024
- 511002916  Waboku (anime)
- 511002917  Realize Defense
 - listed CC as scripter, though no card id yet
- 511002918  Comeback
 - listed Lyris as scripter, though no card id yet
- 511002919  Comic Field
 - listed Lyris as scripter, though no card id yet
- 511002920  Decrease
- 511002921  Devoted Love
 - listed Lyris as scripter, though no card id yet
- 511002922  Drop Exchange
 - listed Lyris as scripter, though no card id yet
- 511002923  Fair Exchange
 - listed Snrk as scripter, id 511008018
- 511002924  Fool's Dice
 - I had also made this one..., id 511005005
- 511002925  Furious Max's Curse
 - listed CC as scripter, id 511009152
- 511002926  Gagaga Thunder
 - I've made this one, id 511005080
- 511002927  Gagagamirror
- 511002928  Golden Form
 - listed Snrk as scripter, id 511008022
- 511002929  Gorgon Charm
 - listed CC as scripter, id 511009151
- 511002930  Guard Plus
 - had made this, id 511005078
- 511002931  Half Guard
- 511002932  Hexa Knight
 - listed CC as scripter, id 511009129
- 511002933  Hollow Spirit
 - listed CC as scripter, id 511009037
- 511002934  Hollow Ghost
 - listed CC as scripter, id 511009039
- 511002935  Joe the Pixie
 - GM is overjoyed as he doesn't need to script this -.-
- 511002936  Illegal Business Practices
- 511002937  Goblin Dancers
 - this one has no revealed effect in anime....
- 511002938  Offerings to the Bound Deity
 - listed CC as scripter, id 511009090
- 511002939  Rescuer from the Grave
- 511002940  Scrap and Build
 - had made this, id 511005061
- 511002941  Small Resistance
 - listed Snrk as scripter, id 511008002
- 511002942  Smoke Mirror
 - had made this, id 511005048
- 511002943  Spirit Mask
 - listed CC as scripter, id 511009161
- 511002944  Superior Howl
 - listed Snrk as scripter, id 511008006
- 511002945  Triple Star Trion (anime)
- 511002946  Tempt to the Crystal
 - had made this, id 511005037
- 511002947  Dimensionhole (anime)
- 511002948  Triangle Knight
 - listed CC as scripter, id 511009127
- 511002949  Trion Barrier
 - listed Snrk as scripter, id 511008011
- 511002950  Inland
 - listed CC as scripter, id 511009163

====

### Fixes:
- 95000047  Action Card - High Dive
- 95000148  Action Card - Extreme Sword
- 511000171  Spell Sanctuary
- 511000198  Enduring Soul
- 511000513  Number 77
 - I don't understand the change. Creating tokens? What are they used for?
- 511000870  Double Delta Warrior
- 511002013  Idaten, the Star of Supreme Victory
- 511002015  Supreme Storm Star Fuujin
- 810000012  Narrow Tunnel
 - while the fix is in the right direction, I think it's a bit different than what the card's text is

====

### Note:
- I didn't look inside the cdb

**Comment by shadowfox87** [comment]
Thank you Shad! This helps a ton. This means only Number 77 and Narrow Tunnel may have wrong effects. I'll note them down in the list. If anyone wants to fix them in the future, they can. It's now good to merge this request.

**Pull request merged**
