### PR TITLE
new anime cards and card pack

### PR DESCRIPTION
**Pull request by urielkama**
[expansions.zip](https://github.com/shadowfox87/animescripts/files/333842/expansions.zip)
[script.zip](https://github.com/shadowfox87/animescripts/files/333843/script.zip)

### CODE REVIEW

**Comment by urielkama** [comment]
new Anime Card scripts and my cdb pack

**Comment by shadowfox87** [comment]
The scripts can't be in a zip file.

**Comment by urielkama** [comment]
ok

**Comment by urielkama** [comment]
in another zip file?

**Comment by shadowfox87** [comment]
No zip necessary. Put scripts in scripts folder and cdb in expansions folder.

**Pull request closed without merging**
